version: "2"
services: 
  gitea: 
    image: gitea/gitea:latest
    container_name: gitea
    hostname: gitea
    domainname: git.${DOMAIN}
    networks:
      ${NETWORK_NAME}:
        ipv4_address: ${IP_PREFIX}.9
    ports:
      - "2222:2222"
      - "3000:3000"
    env_file:
      - ../user_variables.env
    environment:
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=mysql:3306
      - GITEA__database__NAME=${GITEA_DB_NAME} 
      - GITEA__database__USER=${GITEA_DB_USER}
      - GITEA__database__PASSWD=${GITEA_DB_PW}
    links:
      - mysql
    depends_on:
      - mysql
    volumes: 
      - gitea_data:/data
      - gitea_config:/etc/gitea
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    tty: true
    restart: unless-stopped
networks:
  ${NETWORK_NAME}:
    external: true  
volumes:
  gitea_data:
  gitea_config:
