version: "3"
services:
# You need a license for ee, but it is free and worth setting up IMO
  portainer:
    image: portainer/portainer-ee:latest # Change to ce if you have trouble.
    container_name: portainer
    hostname: portainer
    domainname: port.${DOMAIN}
    networks:
      ${NETWORK_NAME}:
        ipv4_address: ${IP_PREFIX}.6
    ports:
      - 8000:8000
      - 9443:9443
    env_file:
      - ../user_variables.env
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    tty: true
    restart: always
networks:
  ${NETWORK_NAME}:
    external: true
volumes:
  data:
