version: "2"
services:
  node:
    image: "node:latest"
    container_name: node_gibbyb
    hostname: node_gibbyb
    domainname: ${DOMAIN}
    networks:
      ${NETWORK_NAME}:
        ipv4_address: ${IP_PREFIX}.24
    ports:
      - 3000:3000
    env_file:
      - ../user_variables.env
    environment:
      - NODE_ENV=production
    volumes:
      - /home/gib/Documents/Web/GibsWebsite:/home/node/app
    user: "node"
    working_dir: /home/node/app
    tty: true
    restart: unless-stopped
networks:
  ${NETWORK_NAME}:
    external: true
